# Generated by Django 3.2.5 on 2021-07-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='home_images/')),
                ('home_text', models.CharField(max_length=300)),
            ],
        ),
    ]
